name: data_server
description: "Data server for price comparison database operations and business logic"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  # HTTP server framework
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  
  # Database ORM and drivers
  drift: ^2.26.1
  sqlite3: ^2.4.0
  
  # JSON handling
  json_annotation: ^4.9.0
  
  # Path utilities
  path: ^1.9.1
  
  # Logging
  logging: ^1.2.0
  
  # Environment variables
  dotenv: ^4.2.0
  
  # HTTP client (for scraper integration)
  http: ^1.1.0
  
  # api_contracts:
  #   path: ../../packages/api_contracts
  shared_models:
    path: ../../packages/shared_models

dev_dependencies:
  # Testing
  test: ^1.24.0
  mockito: ^5.4.6
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.26.1
  
  # Linting
  lints: ^3.0.0

# No flutter section needed - this is a pure Dart server application