# fake values, just to have melos run
name: web_portal
description: "Flutter web portal for price comparison administration"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Local packages (uncomment when you create them)
  # shared_models:
  #   path: ../../packages/shared_models
  # api_contracts:
  #   path: ../../packages/api_contracts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true