name: shared_services
description: "Services de communication inter-serveurs"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.4.0
  lints: ^6.0.0
  shared_models:
    path: ../shared_models

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.0
