name: shared_models
description: Shared data models between client and server
version: 1.0.0
publish_to: none  # This package is not published to pub.dev

environment:
  sdk: ^3.8.0

dependencies:
  json_annotation: ^4.9.0
  drift: ^2.26.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.26.1